README.md

docs: fix link to macOS command line reference book

---

docs/theorist/darts/search_space.md

Just a quick fix to some documentation typos.
Fixes #126  
- Documentation update

minor textual fixes to search_space.md

---

.github/workflows/test.yml
.idea/autora.iml
.idea/misc.xml
poetry.lock
pyproject.toml
tests/test_darts_1d_primitive_recovery.py
tests/test_sklearn_darts.py

Add poetry install and pytest to CI.
Resolves #103 
- Workflow

test: add pytest CI

---

autora/variable/__init__.py
autora/variable/time.py
autora/variable/tinkerforge.py
poetry.lock
pyproject.toml

Simplify the Variable classes drastically, by using data classes, no longer using explicit methods for getting and setting variable values.
- Breaking Change (the parts removed weren't intended to be part of the package, but they are now)
- Simplify Variables, replacing explicit classes with data classes

refactor!: remove dunder methods

---

poetry.lock
pyproject.toml

Add Jupyter as a dev dependency. it's used in the example scripts.

fix: add missing dependency jupyter to dev

---

README.md

Quick fix to README for latest version of PyCharm
Fixes #144 
- Documentation update
- reflects new fields in adding a new Python interpreter to a project

docs: update README.md for new PyCharm interface

---

README.md
conda/recipe/meta.yaml
pyproject.toml

chore: Bump version to 2.1.0

---

.pre-commit-config.yaml
autora/theorist/darts/architect.py
autora/theorist/darts/model_search.py
autora/theorist/darts/plot_utils.py
autora/theorist/darts/utils.py
autora/theorist/darts/visualize.py

Update the mypy pre-commit hook to the newest version.
- Refactoring (non-breaking change which improves the code but doesn't have any functional effect)
- Updated mypy version
- Updated type annotations as required

Chore: bump mypy to 0.991

---

autora/experimentalist/sampler/model_disagreement.py
tests/test_model_disagreement_sampler.py

This feature implements a model disagreement sampler for both classification and regression models.
The sampler computes the predictions for a given sample of independent variables and then identifies the independent variables that yield the highest disagreement between N models. 
The PR comes with two unit tests, one for a classification model and one for a regression model.
_Fixes #(issue)_ (if the issue is on Github, simply link to it using the '#' symbol; otherwise, provide a notion page link)
- New feature (non-breaking change which adds functionality)
- momdel disagreement sampler
- unit test for classification models
- unit test for the regression models

added model disagreement sampler

---

.pre-commit-config.yaml
autora/theorist/darts/model_search.py
autora/theorist/darts/operations.py
tests/test_sklearn_darts.py

Resolves an issue where different operations were constructed using identical parameters in memory, rather than different parameters for each.
resolves #153

fix: convert OPS dictionary into a factory function

---

.github/workflows/py.test.yml

test: run testcases on macos in CI

---

.github/workflows/py.test.yml
tests/README.md
tests/test_poppernet_pooler.py
tests/test_sklearn_darts.py

Make test cases involving neural networks more reproducible.
resolves #202 
resolves #128 
invalidates #204
Type of change:
- Testing update

test: reproducible tests

---

tests/test_darts_1d_primitive_recovery.py

test: add seeding for DARTS tests

---

autora/skl/bms.py
autora/theorist/bms/mcmc.py
autora/theorist/bms/parallel.py
tests/test_bms_custom_primitives.py

Functionality added to BMS that can take in custom primitives in the form of user-defined functions.
_Fixes #(issue)_ (if the issue is on Github, simply link to it using the '#' symbol; otherwise, provide a notion page link)
- New feature (non-breaking change which adds functionality)
- option to add custom primitives added
- Created for general use and to address needs of base branch
- Will need to add tests

add custom primitives for bms

---

autora/skl/bms.py
autora/theorist/bms/mcmc.py
autora/theorist/bms/parallel.py

User can now pass a seed to bms when fitting to make its results replicable
_Fixes #242 _ 
- New feature (non-breaking change which adds functionality)
- new parameter to bms that allows user to fix seed (but doesn't by default)

Fix bms seed

---

.github/workflows/test-pytest.yml

Alternative fix strategy for poetry problems

test: make github action only install main and test dependencies

---

.github/workflows/test-conda-build.yml
.github/workflows/test-poetry-build.yml
.github/workflows/test-pre-commit-hooks.yml
.github/workflows/test-pytest.yml

Run all CI checks on all PRs, not just those to main. Also run checks on all branches in the [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
- Testing update

test: update PR checks to check all PRs before they merge to main

---

mkdocs.yml

Adding BSR to `mkdocs.yml`
resolves #340 

docs: add BSR to mkdocs.yml

---

README.md

Update image path.
We should make a 3.0.1 release after merging this

docs: update image path

---

docs/hooks.py
mkdocs.yml
mkdocs/overrides/main.html
pyproject.toml

docs: add site url (fixes links)

---

docs/tutorials/index.md

Basic content for the `index.md` in tutorials.
- simple, but sufficient?

Add content to index.md for tutorials

---

docs/contribute/core.md
docs/contribute/index.md
docs/contribute/modules/experiment-runner.md
docs/contribute/modules/experimentalist.md
docs/contribute/modules/index.md
docs/contribute/modules/theorist.md
docs/experiment-runner/index.md
mkdocs.yml

455 docs make folder structure consitent with nav in mkdocs.yml

---

docs/contribute/pre-commit-hooks.md
docs/contribute/setup.md

docs: change header case

---

docs/contribute/index.md

- resolves #488 
- placement? 
- do we need to elaborate or is this sufficient for now?

docs: add mention of style guide in top-level of contributor guide

---

docs/contribute/index.md

adhere to [Documentaton Style Guide](https://autoresearch.github.io/autora/contribute/)
- resolves #492

docs: strong title cases in all headings

---

mkdocs.yml

Add documentation on functional tutorial to main site.

docs: add functional tutorial

---

mkdocs.yml
pyproject.toml

adds leverage sampler to parent package
- **feat**: A new feature

feat: add leverage sampler

---

README.md

docs: add MIT license badge to README

---

mkdocs.yml

Include updated workflow documentation from https://github.com/AutoResearch/autora-core/pull/64

docs: update workflow documentation

---

pyproject.toml

remove sampler appendix in the experimentalist dependencies
*If the issue is on Github, simply link to it using the '#' symbol; otherwise, provide a notion page link)*:
- resolves #544

544 update dependencies based on new packages post hackathon

---

pyproject.toml

add optional dependency for synthetic and especially for synthetic-abstract-equation package
- resolves #592

add optional dependency: abstract equation

---

docs/tutorials/basic/Tutorial III Functional Workflow.ipynb
docs/tutorials/basic/Tutorial IV Customization.ipynb
pyproject.toml

update installation/import path of synthetic experiment runner to from "synthetic-..." to "experiment-runner-synthetic-..."
*Don't forget to make a new release after merge*

Chore make synthetic import consistence

---

CITATION.cff

doc: added doi

---

mkdocs.yml

Minor restructure of documentation order

docs: restructure tutorials and examples

---

mkdocs.yml
pyproject.toml

Add bandit random sampler as dependency and include it in the website
- resolves #639

feat: add bandit-random sampler

---

docs/tutorials/Experimentalist.ipynb

Fixed import statement to repair tutorial for experimentalists.
- **fix**: A bug fix

fix: fixed import statement for falsification sampler

---

docs/examples/closed-loop-bandit-task/prolific.md

Typo fix.
- **docs**: Documentation only

doc: Update prolific.md typo fix

---

mkdocs.yml

add code referenc to experiment runner firebase prolific

docs: add experiment runner firebase prolific to code reference

---

CITATION.cff
README.md

Updated repo citation to the joss paper.
Citation file was taken from: https://github.com/openjournals/joss-reviews/issues/6839

doc: updated to joss citation
