- .gitignore
- .idea/.gitignore
- .idea/autora.iml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/encodings.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/other.xml
- .idea/poetry.xml
- .idea/vcs.xml
- autora/cycle/__init__.py
- tests/test_closed_loop.py
- tests/test_cycle.py
Refactored the state machine to not use a run function. The run is now a method of the cycle class and during initialization all parameters are passed as keywords. 
- New feature (non-breaking change which adds functionality)
- Run function for closed-loop cycle
- New container classes: TheoryCollection, RunCollection. These classes hold parameters and aggregate products from the AER cycle. 
- Enum class for key modules 
- I left in state machine graphing functionality with a switch in the state machine initialization. I know we discussed removing the graphing functionality but I figured it could be useful while things are still under development. We can always remove for production.  
- One annoying thing about the transitions package is that it makes encapsulating methods (making them …
> Closed-Loop Run Function

- .pre-commit-config.yaml
Update pre-commit hook "black" to newest.
> Chore/bump black to 22.10.0

- .github/workflows/pre-commit-hooks.yml
- .github/workflows/py.test.yml
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
Potentially fix the issue where myPy doesn't run correctly in CI.
resolves #176 
- CI fix (non-breaking change which fixes an issue)
**Required change:** Split the pre-commit from the py.test workflows, as pre-commit now only works using python 3.8, and py.test workflow has to run under 3.8, 3.9 and 3.10
**Additional change:** refactored some of the workflow code to shorten it and use caching where available.
> test: split pre commit from pytest in ci

- autora/variable/__init__.py
Set variable range default to none so that it doesn't conflict with allowed values.
_Fixes #185(issue)_ 
> set variable range default to none so that it doesn't conflict with allowed values

- .github/workflows/py.test.yml
... to speed up CI checks
- Testing update
Now successfully uses the cache:
> ci: get cacheing working on GitHub workflow pytest

- autora/cycle/simple.py
- tests/test_sklearn_pipeline.py
Fixes the issue #209 where past theories were being overwritten each cycle when using sklearn's Pipeline to construct a Theorist with preprocessing. 
- Changed to use a `deepcopy` instead of `copy` in the simple cycle when copying the Theorist. 
- Added a test file to ensure the memory space of each Theorist's estimators are unique when using sklearn's Pipeline as a theorist.
> 209 deepcopy theorist

- autora/theorist/bms/parallel.py
replace `np.float` with `float`
_Fixes #221_
Required for #213 
> fix: update deprecated use of np.float

- tests/test_cycle_plots.py
Refactored the tests for the cycle plotters to be more efficient. 
* Previously each test was running the cycle passed from a pytest fixture. I moved the running of the cycle into the fixture so that it only needs to run one time. 
* I also split some of the larger tests into smaller tests so errors can be more easily identified and traced.
- Optimization
> Refactor cycle plot tests

- .pre-commit-config.yaml
upgrade the version of isort in `pre-commit-config.yaml` to avoid build failure.
fixes #261 
- bump isort from 5.10.1 to 5.12.0
- is this actually the relevant issue?
- if so, is this where/how it should be fixed (ie, with a simple branch off main)?
- is there anything within dependabot itself that needs to updated?
- first looked at the details of the build failure: https://github.com/AutoResearch/autora/actions/runs/4055928636/jobs/6979735632
- then googled the RunTimeError message, which got me here: https://github.com/home-assistant/core/issues/86892#issuecomment-1407641288
> chore: upgrade isort in pre-commit to avoid build failures

- autora/cycle/plot_utils.py
Replace global modification of matplotlib `rc_params` (which controls plot styling) with a context manager
- refactor
- make it so that only the plots generated from the `plotting` module are affected by the `rc_params` updates (rather than the whole python session)
- Any readability updates we need here?
- Do we rely on these updates anywhere else?
> refactor: use contextmanager to handle RC params in controller/plotting.py

- .github/workflows/publish-documentation-gh-pages.yml
... so they are definitely in sync with those which a user might use locally when writing the docs.
- **fix**: A bug fix
> docs: update documentation building script to use poetry for installing dependencies

- .github/workflows/publish-documentation-gh-pages.yml
Adds trigger to publish documentation every night at 3:59 UTC / 23:59 EST
Fixes #437 
- **ci**: Changes to our CI configuration files and scripts (i.e., those in the .github directory)
- additional event to trigger `publish-documentation-gh-pages.yml`
> ci: add trigger to publish every night

- mkdocs/overrides/main.html
Update button for opening in colab – use the standard button used everywhere.
> docs: update button to open in colab

- docs/contribute/modules/index.md
> docs: update documentation to reflect new structure with code references

- docs/contribute/modules/index.md
Adding small bit of language to make explicit the need to create a new branch for adding a contribution.
- resolves #459 
> Elaborate on PR process for contributions

- docs/contribute/index.md
- docs/contribute/modules/experiment-runner.md
- docs/contribute/modules/experimentalist.md
- docs/contribute/modules/index.md
- docs/contribute/modules/theorist.md
- docs/contribute/pre-commit-hooks.md
- docs/contribute/setup.md
- docs/index.md
- docs/online-experiments/firebase.md
- docs/tutorials/Experimentalist.ipynb
- docs/tutorials/Theorist.ipynb
> Clean up documentation headings globally in parent package

- .github/workflows/publish-documentation-gh-pages.yml
resolves #490 
- **ci**: Changes to our CI configuration files and scripts (i.e., those in the .github directory)
- i'm not entirely sure this is what you [meant](https://autonomousemp-x117217.slack.com/archives/C053US2PP4H/p1687531732057319), @younesStrittmatter. info on `merge_group` trigger can be found here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
> ci: add push-to-main-branch as event to trigger publishing documentation

- mkdocs.yml
- resolves #395
add the documentation from the [user cookiecutter](https://github.com/AutoResearch/autora-user-cookiecutter/blob/main/docs/index.md)
Not exactly a jupiter notebook tutorial. Describes the process of setting up and AutoRA workflow + Firebase Website in a way so they can be used together. 
The cookiecutter basic example will be updated accordingly additionally (this works as an example and gets a closed loop running, but is not updated with some recent changes in the packages)
> docs: include tutorial for online experiment

- mkdocs.yml
i believe this was the only place we refer to "Automated Theorist" and "Automated Experimentalist", so simplifying to conform. eg, under User Guide, it's just "Theorists" and "Experimentalists"
> docs: update page names in tutorials

- docs/index.md
- docs/online-experiments/firebase.md
- docs/tutorials/Experimentalist.ipynb
- docs/tutorials/Theorist.ipynb
- resolves #503
the links in the jupiter notebooks work, but it doesn't seem right. I brievly looked into the mkdocs-jupiter plugin documentation but didn't find much. I'll work on it when I find time, but this is a quick fix so at least it works.
> 503 fix broken links

- docs/contribute/setup.md
- docs/installation.md
- mkdocs.yml
resolves #464 
- not sure where to put this... first page under "User Guide"?
- also not sure what @musslick mean't by the last task -- "We should also consider adding the name of the autora pip/conda package for each tool in the main doc file (index.md) of the respectvie package."
- to me, listing all the optional dependencies seems overkill and likely to get lost in the process of adding new ones going forward. as such, i opted to refer people to the `pyproject.toml` file for a complete list of options. this is comprehensive, and will necessarily be updated as optional dependencies are added. happy to change and create some sort of table, but aiming for effective viable solution that doesn't add documentation liability in the future...
> docs: add installation page to main documentation

- docs/contribute/modules/index.md
add documentation for automatic publishing
solves #519
> docs: add details on publishing via Github Actions

- docs/contribute/modules/index.md
resolves #466 and cleans up the corresponding page a bit.
> docs: add note to contributor documentation for updating and releasing new versions of contributed modules.

- .github/labels.yml
- .github/workflows/sync-labels.yml
resolves #530 
- **ci**: Changes to our CI configuration files and scripts (i.e., those in the .github directory)
- thoughts on the best way to handle the third task — adding documentation / codifying a workflow to update and run the action when a new repo is created?
> ci: standardize repository issue labels with label syncer

- mkdocs.yml
Updated the nav as the basic tutorials were renamed in the last PR.
- resolves #569 
- **fix**: A bug fix
- mkdocs serve fails locally, something to do with my path, so my new nav is untested. I'll work on getting it running but the new nav shoooould be fine.
> fix: Updated nav for basic tutorials

- CITATION.cff
Added citation info according to GitHub conventions. Note: currently the citation info only lists "official" code maintainers. We will discuss the list once we submit the corresponding article.
> doc: added citation info

- mkdocs.yml
add code references for autora-synthetic module (we need eventually should add the optional ones too)
- resolves #603
> doc: add code references for synthetic runners

- docs/tutorials/basic/Tutorial III Functional Workflow.ipynb
- docs/tutorials/basic/Tutorial IV Customization.ipynb
Rename `experiment_runner` function in abstract equation runner to `run`.
See: 
- https://github.com/AutoResearch/autora-synthetic-abstract-equation/pull/4
(if reviewing this, please aprove, merge and release https://github.com/AutoResearch/autora-synthetic-abstract-equation/pull/4 first)
docs only change. no need for a new release of autora parent
> rename experiment_runner to run in abstract equation runner

- docs/contribute/modules/experimentalist.md
> docs: remove distinction between poolers and samplers in experimentalist.md

- docs/contribute/core.md
- docs/contribute/index.md
- docs/contribute/modules/experimentalist.md
- docs/contribute/modules/index.md
- docs/contribute/modules/theorist.md
This PR updates the contributor guide to the current version of autora 4.0.0 (see detailed list of fixed below). 
- resolves #625 
- resolves #557 
- removal of the `autora-workflow` package from the description of core packeges.
- updated examples of theorist and experimentalist implementations, primarily to be based on pandas dataframes
- added requirement for contributor repo to be public for inclusion in autora package
- In the modules/index.md the lists inside the Success and Hint boxes aren't rendering properly. They are just listed without a line brak. I tried changing the "-" to "*" but not sure if that fixed it?
> docs: updated contributor guide

- mkdocs.yml
add the links to the abstract equation runner (examples + code references) to the website
We import the index.md file for the synthetic documentation from the synthetic-repo. It basically only contains links to the code references. I think instead we should create a index.md file in the autora_parent repo (since the links don't make sense in the synthetic repo anyway). We are more flexible then (for example could add references to contributors more easily)
> docs: add equation runner to examples and code reference

- docs/tutorials/basic/Tutorial Ia Theorists.ipynb
- docs/tutorials/basic/Tutorial Ib Experimentalists.ipynb
Fixed non-local hyperlinks in the basic tutorials notebooks.
> docs: fixed links in basic tutorial notebooks

- docs/examples/closed-loop-basic/notebooks/sweetbean.ipynb
Fixes a missing import statement in the sweetbean notebook from the closed-loop example. 
> docs: fixed missing import statement in notebooks

- docs/examples/closed-loop-bandit-task/init_autora.md
- docs/examples/closed-loop-bandit-task/setup.md
- docs/examples/closed-loop-bandit-task/testingzone.md
- docs/examples/closed-loop-basic/init_autora.md
- docs/examples/closed-loop-basic/setup.md
- docs/examples/closed-loop-basic/testingzone.md
- Fixed a github repo link in the doc
- Added sudo hints for installing firebase and setting up the cookiecutter template. I encountered an installation issue on a local setup but running the same commands with sudo fixed it.
> docs: fixed links and added sudo hints

- README.md
- docs/index.md
Added citation info in readme and doc index so that there is a pointer to the paper and bibtex entry.
> doc: added citation info in readme and doc index
